server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: laptopshop2024@gmail.com
    password: izyk gzed gywt lsya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  application:
    name: datn_be
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/dbo_datn?useSSL=false&serverTimezone=UTC
    username: root
    password: levansy190104
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
khang:
  jwt:
    base64-secret: ZNsuIEYem0dC12lgBymX2bCpRj8V2FYIJyVdwNjsCr+aZD4xVya98ZmdS9Yv5xwYjTzdQReKJDq5E76AxMebzQ==
    access-token-validity-in-seconds: 900     # 15 minutes = 900 seconds
    refresh-token-validity-in-seconds: 604800  # 7 days = 604800 seconds
  upload-file:

    base-uri: file:///D:/DATN_LAPTOPSTORE/Datn_LapTopShop/upload/
    #"D:\datn\datn_fpoly\upload"
stripe:
  api:
    key: sk_test_51Q4i0kCsOTWfrG9wJicEj5K728Kfg51NJRNkHJ6w1OXpkiZttpWvPyzfu8AHGQE2Okk5wYkZjm6Ml8sMIe5w1q9v00UgyWcGqF

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: BAI2QNS0
    secretKey: 4TWEULGX5857FVHOJ9B57N3KKSGAK1ME
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other